platform :ios, '8.0'
use_frameworks!
pod 'Alamofire', '~> 1.2.3'
pod 'WeiboSDK', '~> 3.0.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SZTextView', '~> 1.2.1'
pod 'RMDateSelectionViewController', '~> 2.0.1'
pod 'SDWebImage', '~>3.7'
pod 'RealmSwift', '~> 0.95.0'

link_with 'pigeon'